import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Eye, RefreshCw } from "lucide-react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { AppBreadcrumbs } from "@/components/layout/AppBreadcrumbs";
import { domainEventsAPI, type DomainEvent } from "@/services/domain-events";

const EVENT_TYPES = ["lead.created", "lead.updated", "lead.status_changed", "lead.pipeline_stage_changed", "lead.tag_added", "lead.tag_removed", "lead.assigned", "lead.converted", "activity.created", "activity.completed"];
const formatDate = (value: string) => new Date(value).toLocaleString("pt-BR");

export function DomainEventsPage() {
  const [events, setEvents] = useState<DomainEvent[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [eventType, setEventType] = useState("all"); const [entityType, setEntityType] = useState(""); const [entityId, setEntityId] = useState(""); const [selected, setSelected] = useState<DomainEvent | null>(null);
  const load = async (nextPage = page) => { setLoading(true); setError(null); try { const result = await domainEventsAPI.list({ page: nextPage, page_size: 25, event_type: eventType === "all" ? undefined : eventType, entity_type: entityType, entity_id: entityId }); setEvents(result.events); setPage(result.pagination.page); setTotalPages(result.pagination.totalPages || 1); setTotal(result.pagination.total); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar os eventos."); } finally { setLoading(false); } };
  useEffect(() => { void load(1); }, [eventType]);
  const applyFilters = () => { void load(1); };
  return <div className="space-y-5 p-4 md:p-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><AppBreadcrumbs /><div className="mt-3 flex items-center gap-2"><Button asChild variant="ghost" size="icon" title="Voltar"><Link to="/comercial/automacoes"><ChevronLeft className="h-4 w-4" /></Link></Button><div><h1 className="text-2xl font-semibold">Eventos</h1><p className="text-sm text-muted-foreground">Observe os eventos de domínio registrados pelo CRM.</p></div></div></div><Button variant="outline" size="icon" title="Atualizar" onClick={() => void load()}><RefreshCw className="h-4 w-4" /></Button></div>
    <Card className="rounded-lg border shadow-none"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_180px_150px_auto] md:items-end"><div className="space-y-2"><Label>Tipo de evento</Label><Select value={eventType} onValueChange={setEventType}><SelectTrigger><SelectValue placeholder="Todos os eventos" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os eventos</SelectItem>{EVENT_TYPES.map((type) => <SelectItem key={type} value={type}>{type}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Entidade</Label><Input value={entityType} onChange={(e) => setEntityType(e.target.value)} placeholder="lead" /></div><div className="space-y-2"><Label>ID</Label><Input value={entityId} onChange={(e) => setEntityId(e.target.value)} placeholder="123" /></div><Button onClick={applyFilters}>Filtrar</Button></CardContent></Card>
    {error && <Alert variant="destructive"><AlertTitle>Erro ao carregar eventos</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}
    <Card className="rounded-lg border shadow-none"><CardHeader><CardTitle className="text-base">{total} eventos</CardTitle></CardHeader><CardContent className="p-0">{loading ? <div className="space-y-3 p-5"><Skeleton className="h-8 w-full" /><Skeleton className="h-8 w-full" /><Skeleton className="h-8 w-full" /></div> : events.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">Nenhum evento encontrado.</p> : <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Data/hora</TableHead><TableHead>Evento</TableHead><TableHead>Entidade</TableHead><TableHead>Ator</TableHead><TableHead>Correlation ID</TableHead><TableHead>Ação</TableHead></TableRow></TableHeader><TableBody>{events.map((event) => <TableRow key={event.id}><TableCell className="whitespace-nowrap">{formatDate(event.occurred_at)}</TableCell><TableCell><Badge variant="outline">{event.event_type}</Badge></TableCell><TableCell>{event.entity_type} #{event.entity_id}</TableCell><TableCell>{event.actor_name || "Sistema"}</TableCell><TableCell className="max-w-[220px] truncate font-mono text-xs">{event.correlation_id || "-"}</TableCell><TableCell><Button variant="ghost" size="icon" title="Ver detalhes" onClick={() => void domainEventsAPI.get(event.id).then((result) => setSelected(result.event)).catch((e) => toast.error(e instanceof Error ? e.message : "Não foi possível carregar o evento."))}><Eye className="h-4 w-4" /></Button></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card>
    <div className="flex items-center justify-end gap-2"><Button variant="outline" size="icon" title="Página anterior" disabled={page <= 1 || loading} onClick={() => void load(page - 1)}><ChevronLeft className="h-4 w-4" /></Button><span className="text-sm text-muted-foreground">Página {page} de {totalPages}</span><Button variant="outline" size="icon" title="Próxima página" disabled={page >= totalPages || loading} onClick={() => void load(page + 1)}><ChevronRight className="h-4 w-4" /></Button></div>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{selected?.event_type}</DialogTitle><DialogDescription>{selected?.event_uuid} · {selected && formatDate(selected.occurred_at)}</DialogDescription></DialogHeader>{selected && <div className="space-y-3 text-sm"><div><p className="text-xs text-muted-foreground">Causation ID</p><p className="break-all font-mono text-xs">{selected.causation_id || "-"}</p></div><div><p className="text-xs text-muted-foreground">Correlation ID</p><p className="break-all font-mono text-xs">{selected.correlation_id || "-"}</p></div><pre className="max-h-[420px] overflow-auto rounded-md border bg-muted/20 p-4 text-xs">{JSON.stringify(selected.payload || {}, null, 2)}</pre></div>}</DialogContent></Dialog>
  </div>;
}
