import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ExternalLink, Loader2, Search, ShieldCheck } from "lucide-react";
import { AppBreadcrumbs } from "@/components/layout/AppBreadcrumbs";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { websiteDiagnosticsApi } from "@/services/website-diagnostics";
import type { WebsiteDiagnostic } from "@/types/website-diagnostic";

const statusLabel: Record<string, string> = { pending: "Na fila", processing: "Analisando", completed: "Concluído", partial: "Parcial", failed: "Falhou" };
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "-";

export function WebsiteDiagnosticsPage() {
  const [url, setUrl] = useState(""); const [items, setItems] = useState<WebsiteDiagnostic[]>([]); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const navigate = useNavigate();
  const load = () => websiteDiagnosticsApi.list().then((result) => setItems(result.diagnostics)).finally(() => setLoading(false));
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!url.trim()) return; setSubmitting(true); try { const result = await websiteDiagnosticsApi.create(url.trim()); setUrl(""); navigate(`/comercial/diagnostico/${result.id}`); } finally { setSubmitting(false); } };
  return <div className="space-y-6 p-4 md:p-6"><AppBreadcrumbs /><div><h1 className="text-3xl font-bold">Diagnóstico de site</h1><p className="text-muted-foreground">Analise a presença digital de um domínio com os dados disponíveis no CRM.</p></div><Card><CardHeader><CardTitle className="text-base">Novo diagnóstico</CardTitle></CardHeader><CardContent><form className="flex flex-col gap-3 md:flex-row" onSubmit={submit}><Input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.exemplo.com.br" type="url" required /><Button disabled={submitting}>{submitting ? <Loader2 className="animate-spin" /> : <Search />} Analisar site</Button></form></CardContent></Card><section className="space-y-3"><h2 className="text-lg font-semibold">Histórico recente</h2>{loading ? <p className="text-sm text-muted-foreground">Carregando diagnósticos...</p> : items.length === 0 ? <Card><CardContent className="p-6 text-sm text-muted-foreground">Nenhum diagnóstico realizado ainda.</CardContent></Card> : items.map((item) => <Link className="block" key={item.id} to={`/comercial/diagnostico/${item.id}`}><Card className="transition-colors hover:border-primary/60"><CardContent className="flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{item.domain}</p><p className="text-sm text-muted-foreground">{item.url}</p><p className="text-xs text-muted-foreground">{formatDate(item.created_at)}</p></div><div className="flex items-center gap-3"><Badge variant="outline">{statusLabel[item.status] || item.status}</Badge><span className="text-sm font-medium">{item.overall_score == null ? "Score pendente" : `${item.overall_score}/100`}</span></div></CardContent></Card></Link>)}</section></div>;
}

function Indicator({ label, value }: { label: string; value: unknown }) { return <div className="flex items-center justify-between border-b border-border/60 py-2 text-sm"><span>{label}</span><span className="font-medium">{typeof value === "boolean" ? (value ? "Sim" : "Não") : value == null ? "Não disponível" : String(value)}</span></div>; }
export function WebsiteDiagnosticDetailPage() {
  const { id } = useParams(); const [item, setItem] = useState<WebsiteDiagnostic | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; const load = async () => { try { const result = await websiteDiagnosticsApi.get(id || ""); if (active) setItem(result.diagnostic); } catch (reason) { if (active) setError(reason instanceof Error ? reason.message : "Erro ao carregar diagnóstico."); } }; void load(); const timer = setInterval(() => { if (item && !["pending", "processing"].includes(item.status)) return; void load(); }, 5000); return () => { active = false; clearInterval(timer); }; }, [id, item?.status]);
  if (error) return <div className="p-6"><p className="text-destructive">{error}</p></div>; if (!item) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="animate-spin" /></div>;
  const performance = item.performance || { status: "unavailable", score: null, message: "Análise de performance ainda não disponível." }; const security = item.security || {};
  return <div className="space-y-6 p-4 md:p-6"><AppBreadcrumbs /><Link className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground" to="/comercial/diagnostico"><ArrowLeft className="h-4 w-4" /> Voltar para diagnósticos</Link><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h1 className="text-3xl font-bold">{item.domain}</h1><a className="inline-flex items-center gap-1 text-sm text-primary" href={item.normalized_url} target="_blank" rel="noreferrer">{item.url}<ExternalLink className="h-3 w-3" /></a></div><Badge variant="outline">{statusLabel[item.status] || item.status}</Badge></div><div className="grid gap-4 md:grid-cols-4">{[["Visão geral", item.overall_score == null ? "-" : `${item.overall_score}/100`], ["Páginas analisadas", item.pages_analyzed], ["Performance", performance.score == null ? "Indisponível" : `${performance.score}/100`], ["Atualizado", formatDate(item.completed_at || item.created_at)]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Indicadores</CardTitle></CardHeader><CardContent><Indicator label="SEO" value={item.seo ? "Analisado" : null} /><Indicator label="Experiência e mobile" value={item.mobile ? "Analisado" : null} /><Indicator label="Segurança" value={security.https} /><Indicator label="Tecnologias" value={item.technology ? "Identificadas" : null} /><Indicator label="Rastreamento" value={item.tracking ? "Analisado" : null} /></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4 text-primary" /> Performance</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{performance.message || "Análise de performance ainda não disponível."}</p></CardContent></Card></div><Card><CardHeader><CardTitle className="text-base">Oportunidades identificadas</CardTitle></CardHeader><CardContent className="space-y-3">{(item.gaps || []).length ? item.gaps?.map((gap) => <div className="rounded-md border border-border/70 p-3" key={gap.id}><p className="font-medium">{gap.title}</p><p className="text-sm text-muted-foreground">{gap.description}</p><p className="mt-1 text-xs text-primary">{gap.recommendation}</p></div>) : <p className="text-sm text-muted-foreground">Nenhuma oportunidade adicional foi identificada.</p>}</CardContent></Card></div>;
}
