import { useEffect, useRef, useState } from "react";
import { Loader2, Search } from "lucide-react";
import { AppBreadcrumbs } from "@/components/layout/AppBreadcrumbs";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { websiteDiagnosticsApi } from "@/services/website-diagnostics";
import type { WebsiteDiagnostic } from "@/types/website-diagnostic";

const formatError = (error: unknown) => error instanceof Error ? error.message : "Não foi possível concluir a análise.";
const formatDate = () => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date());

function Indicator({ label, value }: { label: string; value: unknown }) { return <div className="flex items-center justify-between border-b border-border/60 py-2 text-sm"><span>{label}</span><span className="font-medium">{typeof value === "boolean" ? (value ? "Sim" : "Não") : value == null ? "Não disponível" : String(value)}</span></div>; }

export function WebsiteDiagnosticsPage() {
  const [url, setUrl] = useState(""); const [result, setResult] = useState<WebsiteDiagnostic | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const controllerRef = useRef<AbortController | null>(null);
  useEffect(() => () => controllerRef.current?.abort(), []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (loading || !url.trim()) return; controllerRef.current?.abort(); const controller = new AbortController(); controllerRef.current = controller; setLoading(true); setError(null); setResult(null); try { const response = await websiteDiagnosticsApi.analyze(url.trim(), controller.signal); setResult(response.result); } catch (reason) { if (!controller.signal.aborted) setError(formatError(reason)); } finally { if (!controller.signal.aborted) setLoading(false); } };
  return <div className="space-y-6 p-4 md:p-6"><AppBreadcrumbs /><div><h1 className="text-3xl font-bold">Diagnóstico de site</h1><p className="text-muted-foreground">Análise pontual baseada nas páginas públicas acessíveis do domínio.</p></div><Card><CardHeader><CardTitle className="text-base">Analisar um site</CardTitle></CardHeader><CardContent><form className="flex flex-col gap-3 md:flex-row" onSubmit={submit}><Input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.exemplo.com.br" type="url" required disabled={loading} /><Button disabled={loading || !url.trim()}>{loading ? <Loader2 className="animate-spin" /> : <Search />} {loading ? "Analisando site..." : "Analisar site"}</Button></form>{loading ? <p className="mt-3 text-sm text-muted-foreground">O diagnóstico pode levar alguns segundos. Até 5 páginas serão analisadas.</p> : null}{error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}</CardContent></Card>{result ? <DiagnosticResult result={result} /> : null}</div>;
}

function DiagnosticResult({ result }: { result: WebsiteDiagnostic }) { const security = result.security || {}; const performance = result.performance || { score: null, message: "Análise de performance ainda não disponível." }; return <section className="space-y-4"><div className="flex items-end justify-between"><div><h2 className="text-xl font-semibold">Resultado da análise</h2><p className="text-sm text-muted-foreground">{result.summary?.domain || "Domínio analisado"} · {formatDate()}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Qualidade técnica</p><p className="text-2xl font-bold">{result.overallScore == null ? "-" : `${result.overallScore}/100`}</p></div></div><div className="grid gap-4 md:grid-cols-4">{[["Páginas analisadas", result.pagesAnalyzed], ["Performance", performance.score == null ? "Indisponível" : `${performance.score}/100`], ["SEO", result.seo ? "Analisado" : "-"], ["Segurança", security.https === true ? "HTTPS" : "-" ]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Indicadores técnicos</CardTitle></CardHeader><CardContent><Indicator label="HTTPS" value={security.https} /><Indicator label="Viewport" value={(result.mobile as Record<string, unknown> | null)?.viewport} /><Indicator label="Title" value={(result.seo as Record<string, unknown> | null)?.titlePresent} /><Indicator label="Meta description" value={(result.seo as Record<string, unknown> | null)?.metaDescriptionPresent} /></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Performance</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{performance.message || "Análise de performance ainda não disponível."}</p></CardContent></Card></div><Card><CardHeader><CardTitle className="text-base">Oportunidades comerciais</CardTitle></CardHeader><CardContent className="space-y-2">{(result.commercialOpportunities || []).length ? result.commercialOpportunities?.map((item) => <div className="rounded-md border border-border/70 p-3" key={item.id}><p className="font-medium">{item.title}</p><p className="text-sm text-muted-foreground">{item.description}</p><p className="mt-1 text-xs text-primary">{item.recommendation}</p></div>) : <p className="text-sm text-muted-foreground">Nenhuma oportunidade adicional foi destacada nesta análise.</p>}</CardContent></Card></section>; }
