import { useEffect, useRef, useState } from "react";
import { Check, CheckCheck, Clock3, Copy, Download, FileText, Image as ImageIcon, MessageSquareReply, MoreHorizontal, Play, Volume2, X } from "lucide-react";
import { conversationMediaUrl, type CommunicationMessage } from "@/api/conversations";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { ChannelCapability } from "@/lib/channel-capabilities";

type Props = { message: CommunicationMessage; conversationId: number; isGroup?: boolean; capabilities: ChannelCapability; quoted?: CommunicationMessage | null; onReply: (message: CommunicationMessage) => void; onCopy: (message: CommunicationMessage) => void; onOpenMedia: (url: string) => void };
const labels: Record<string, string> = { image: "Foto", audio: "Áudio", video: "Vídeo", document: "Documento", sticker: "Sticker", unknown: "Tipo de mensagem ainda não suportado." };
function mediaUrl(conversationId: number, messageId: number) { return conversationMediaUrl(conversationId, messageId); }
function formatBytes(value?: number | null) { if (!value) return ""; if (value < 1024 * 1024) return `${Math.max(1, Math.round(value / 1024))} KB`; return `${(value / 1024 / 1024).toFixed(1)} MB`; }
function formatDuration(value?: number | null) { if (!value) return ""; return `${Math.floor(value / 60)}:${String(Math.floor(value % 60)).padStart(2, "0")}`; }
export function useAuthenticatedMediaUrl(url: string, enabled: boolean, mimeType?: string | null) { const [objectUrl, setObjectUrl] = useState<string | null>(null); const [failed, setFailed] = useState(false); useEffect(() => { if (!enabled) return; let active = true; const controller = new AbortController(); const token = localStorage.getItem("token"); setFailed(false); fetch(url, { headers: token ? { Authorization: `Bearer ${token}` } : {}, signal: controller.signal }).then((response) => { if (!response.ok) throw new Error(`HTTP_${response.status}`); return response.blob(); }).then((blob) => { if (!active) return; setObjectUrl(URL.createObjectURL(new Blob([blob], { type: mimeType || blob.type || "application/octet-stream" }))); }).catch(() => { if (active) setFailed(true); }); return () => { active = false; controller.abort(); setObjectUrl((current) => { if (current) URL.revokeObjectURL(current); return null; }); }; }, [enabled, mimeType, url]); return { objectUrl, failed }; }

export function ChatMessage({ message, conversationId, isGroup, capabilities, quoted, onReply, onCopy, onOpenMedia }: Props) {
  const outbound = message.direction === "outbound";
  const type = message.message_type || "unknown";
  const url = mediaUrl(conversationId, message.id);
  const protectedMedia = ["image", "video", "audio", "document", "sticker"].includes(type);
  const { objectUrl, failed } = useAuthenticatedMediaUrl(url, protectedMedia, message.media_mime_type);
  const content = protectedMedia && !objectUrl ? failed ? <MediaFallback label="Mídia indisponível." /> : <span className="block p-4 text-xs text-muted-foreground">Carregando mídia...</span> : type === "image" ? <button type="button" className="block max-w-[280px] overflow-hidden rounded-md" onClick={() => objectUrl && onOpenMedia(objectUrl)}><img src={objectUrl || undefined} loading="lazy" alt={message.media_filename || "Imagem recebida"} className="max-h-72 w-full object-cover" /></button> : type === "video" ? <video className="max-h-72 max-w-[300px] rounded-md" src={objectUrl || undefined} controls playsInline preload="metadata" /> : type === "audio" ? <AudioMessage url={objectUrl || ""} duration={message.media_duration_seconds} /> : type === "document" ? <a href={objectUrl || undefined} download={message.media_filename || "documento"} className="flex min-w-[220px] items-center gap-3 rounded-md border bg-background/60 p-3"><FileText className="h-8 w-8 shrink-0 text-primary" /><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{message.media_filename || "Documento"}</strong><span className="text-xs text-muted-foreground">{message.media_mime_type?.split("/").pop()?.toUpperCase() || "Arquivo"}{message.media_size_bytes ? ` · ${formatBytes(message.media_size_bytes)}` : ""}</span></span><Download className="h-4 w-4 shrink-0" /></a> : type === "sticker" ? <img src={objectUrl || undefined} loading="lazy" alt="Sticker" className="max-h-40 max-w-[180px] object-contain" /> : type === "unknown" ? <div className="flex items-center gap-2 text-xs text-muted-foreground"><MoreHorizontal className="h-4 w-4" />{labels.unknown}</div> : <p className="whitespace-pre-wrap break-words">{message.body_text || "Mensagem vazia"}</p>;
  return <div id={`message-${message.id}`} className={cn("group flex scroll-mt-4", outbound ? "justify-end" : "justify-start")}><div className={cn("relative max-w-[78%] rounded-lg px-3 py-2 text-sm shadow-sm", outbound ? "rounded-br-sm bg-primary text-primary-foreground" : "rounded-bl-sm border bg-card")}>{isGroup && !outbound && message.sender_name ? <p className="mb-1 text-xs font-semibold text-primary">{message.sender_name}</p> : null}<div className="mb-1 flex items-center gap-1 opacity-0 transition-opacity group-hover:opacity-100">{capabilities.canReply ? <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => onReply(message)} aria-label="Responder" title="Responder"><MessageSquareReply className="h-3.5 w-3.5" /></Button> : null}{type === "text" ? <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => onCopy(message)} aria-label="Copiar mensagem" title="Copiar mensagem"><Copy className="h-3.5 w-3.5" /></Button> : null}</div>{quoted ? <div className="mb-2 border-l-2 border-primary/60 bg-background/20 px-2 py-1 text-xs opacity-80"><span className="block font-medium">{quoted.direction === "outbound" ? "Você" : quoted.sender_name || "Contato"}</span><span className="line-clamp-2">{quoted.body_text || labels[quoted.message_type || "unknown"] || "Mensagem"}</span></div> : null}{content}{message.body_text && type !== "text" ? <p className="mt-2 whitespace-pre-wrap break-words">{message.body_text}</p> : null}<div className={cn("mt-1 flex items-center justify-end gap-1 text-[10px]", outbound ? "text-primary-foreground/70" : "text-muted-foreground")}><span>{new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(message.created_at))}</span>{outbound && capabilities.canShowReadReceipts ? <DeliveryReceipt status={message.delivery_status} /> : null}</div></div></div>;
}

function DeliveryReceipt({ status }: { status?: string | null }) { const value = String(status || "").toLowerCase(); if (value === "failed") return <span title="Falha ao enviar" aria-label="Falha ao enviar"><X className="h-3 w-3 text-destructive" /></span>; if (value === "read") return <span title="Lido" aria-label="Lido"><CheckCheck className="h-3 w-3 text-sky-500" /></span>; if (value === "delivered") return <span title="Entregue" aria-label="Entregue"><CheckCheck className="h-3 w-3" /></span>; if (value === "sent") return <span title="Enviado" aria-label="Enviado"><Check className="h-3 w-3" /></span>; if (["pending", "sending", "queued", ""].includes(value)) return <span title="Enviando" aria-label="Enviando"><Clock3 className="h-3 w-3" /></span>; return null; }

function AudioMessage({ url, duration }: { url: string; duration?: number | null }) { const ref = useRef<HTMLAudioElement | null>(null); const [rate, setRate] = useState(1); const [playing, setPlaying] = useState(false); const toggle = () => { if (!ref.current) return; if (playing) void ref.current.pause(); else void ref.current.play(); setPlaying(!playing); }; return <div className="flex min-w-[245px] items-center gap-2"><audio ref={ref} src={url} preload="metadata" onEnded={() => setPlaying(false)} className="hidden" /><Button type="button" variant="secondary" size="icon" className="h-8 w-8 shrink-0" onClick={toggle} aria-label={playing ? "Pausar áudio" : "Reproduzir áudio"} title={playing ? "Pausar áudio" : "Reproduzir áudio"}>{playing ? <Volume2 className="h-4 w-4" /> : <Play className="h-4 w-4" />}</Button><div className="h-1.5 flex-1 rounded-full bg-current/20"><div className="h-full w-1/3 rounded-full bg-current/60" /></div><span className="text-xs">{formatDuration(duration)}</span><select value={rate} onChange={(event) => { const value = Number(event.target.value); setRate(value); if (ref.current) ref.current.playbackRate = value; }} className="rounded border bg-transparent px-1 py-0.5 text-xs"><option value={1}>1x</option><option value={1.5}>1.5x</option><option value={2}>2x</option></select></div>; }
function MediaFallback({ label }: { label: string }) { return <span className="flex items-center gap-2 p-4 text-xs text-muted-foreground"><ImageIcon className="h-4 w-4" />{label}</span>; }
