const express = require('express');
const { authenticateToken } = require('../middleware/auth');
const { requireCommercialAccess, requireCommercialAdmin } = require('../middleware/commercial-access');
const { getPool } = require('../config/database');
const { encryptSecret, SUPPORTED_PROVIDERS, listModels, testProvider, invalidateModelCache } = require('../services/ai-provider');

const router = express.Router();
router.use(authenticateToken, requireCommercialAccess);
const publicRow = (row) => ({ provider: row.provider, displayName: row.display_name, configured: Boolean(row.secret_ciphertext), status: row.status, lastTestedAt: row.last_tested_at || null, lastTestStatus: row.last_test_status || null, lastError: row.last_error || null });

router.get('/providers', async (_req, res) => { try { const [rows] = await getPool().execute("SELECT provider, display_name, status, secret_ciphertext, last_tested_at, last_test_status, last_error FROM integration_providers WHERE provider IN ('openai','gemini') ORDER BY provider"); const byProvider = new Map(rows.map((row) => [row.provider, publicRow(row)])); res.json({ providers: SUPPORTED_PROVIDERS.map((provider) => byProvider.get(provider) || { provider, displayName: provider === 'gemini' ? 'Google Gemini' : 'OpenAI', configured: false, status: 'not_configured', lastTestedAt: null, lastTestStatus: null, lastError: null }) }); } catch (error) { res.status(500).json({ error: 'Nao foi possivel carregar os provedores de IA.' }); } });
router.put('/providers/:provider', requireCommercialAdmin, async (req, res) => { const provider = String(req.params.provider); if (!SUPPORTED_PROVIDERS.includes(provider)) return res.status(400).json({ error: 'Provedor de IA nao suportado.' }); const apiKey = String(req.body?.apiKey || '').trim(); if (!apiKey) return res.status(400).json({ error: 'Informe uma API Key ou mantenha o campo vazio para preservar a atual.' }); try { const envelope = encryptSecret({ apiKey }); await getPool().execute(`INSERT INTO integration_providers (provider, display_name, status, configuration_metadata, secret_ciphertext, secret_iv, secret_auth_tag) VALUES (?, ?, 'configured', '{}', ?, ?, ?) ON DUPLICATE KEY UPDATE status = 'configured', secret_ciphertext = VALUES(secret_ciphertext), secret_iv = VALUES(secret_iv), secret_auth_tag = VALUES(secret_auth_tag), updated_at = CURRENT_TIMESTAMP`, [provider, provider === 'gemini' ? 'Google Gemini' : 'OpenAI', envelope.ciphertext, envelope.iv, envelope.authTag]); invalidateModelCache(provider); const [rows] = await getPool().execute('SELECT provider, display_name, status, secret_ciphertext, last_tested_at, last_test_status, last_error FROM integration_providers WHERE provider = ?', [provider]); res.json({ provider: publicRow(rows[0]) }); } catch (error) { res.status(500).json({ error: 'Nao foi possivel salvar a credencial do provedor.' }); } });
router.get('/providers/:provider/models', async (req, res) => { try { res.json({ models: await listModels(String(req.params.provider), { refresh: req.query.refresh === 'true' }) }); } catch (error) { res.status(error.code === 'AI_PROVIDER_NOT_CONFIGURED' ? 409 : 502).json({ error: error.message, code: error.code }); } });
router.post('/providers/:provider/test', requireCommercialAdmin, async (req, res) => { const provider = String(req.params.provider); try { const result = await testProvider(provider); await getPool().execute("UPDATE integration_providers SET status = 'connected', last_tested_at = UTC_TIMESTAMP(), last_test_status = 'success', last_error = NULL WHERE provider = ?", [provider]); res.json(result); } catch (error) { await getPool().execute("UPDATE integration_providers SET last_tested_at = UTC_TIMESTAMP(), last_test_status = 'error', last_error = ? WHERE provider = ?", [String(error.message || 'Falha').slice(0, 200), provider]).catch(() => {}); res.status(502).json({ error: error.message || 'Nao foi possivel testar o provedor.', code: error.code }); } });
module.exports = router;
