CREATE TABLE IF NOT EXISTS website_diagnostics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  prospect_id BIGINT UNSIGNED NULL,
  url VARCHAR(2048) NOT NULL,
  normalized_url VARCHAR(2048) NOT NULL,
  domain VARCHAR(255) NOT NULL,
  status ENUM('pending','processing','completed','partial','failed') NOT NULL DEFAULT 'pending',
  overall_score TINYINT UNSIGNED NULL,
  summary_payload JSON NULL,
  seo_payload JSON NULL,
  performance_payload JSON NULL,
  mobile_payload JSON NULL,
  security_payload JSON NULL,
  technology_payload JSON NULL,
  tracking_payload JSON NULL,
  conversion_payload JSON NULL,
  social_payload JSON NULL,
  gaps_payload JSON NULL,
  recommendations_payload JSON NULL,
  pages_analyzed INT UNSIGNED NOT NULL DEFAULT 0,
  attempt_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  last_error VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_website_diagnostics_owner_created (owner_user_id, created_at),
  KEY idx_website_diagnostics_queue (status, available_at, id),
  KEY idx_website_diagnostics_prospect (prospect_id),
  CONSTRAINT fk_website_diagnostics_owner FOREIGN KEY (owner_user_id) REFERENCES users(id),
  CONSTRAINT fk_website_diagnostics_prospect FOREIGN KEY (prospect_id) REFERENCES prospects(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
