export type Conversation = { id: number; lead_id?: number | null; lead_name?: string | null; lead_phone?: string | null; lead_email?: string | null; lead_website?: string | null; lead_status?: string | null; lead_origin?: string | null; account_name?: string | null; account_phone?: string | null; assigned_user_id?: number | null; assigned_user_name?: string | null; status: string; handling_mode: string; unread_count: number; last_message_at?: string | null; last_message_text?: string | null; last_message_direction?: string | null };
export type CommunicationMessage = { id: number; direction: string; body_text?: string | null; delivery_status?: string | null; message_type?: string | null; created_at: string; sent_at?: string | null; provider?: string | null };
export type ConversationDetail = Conversation & { ai_agent_id?: number | null; lead_city?: string | null; lead_state?: string | null; lead_category?: string | null; lead_created_at?: string | null; assigned_user_email?: string | null };
export type ConversationActivity = { id: number; title: string; description?: string | null; type: string; created_at: string; actor_name?: string | null };
const base = () => import.meta.env.PROD ? (import.meta.env.VITE_API_BASE_URL || window.location.origin).replace(/\/api\/?$/, '').replace(/\/+$/, '') : 'http://localhost:3001';
const request = async <T>(path: string, options: RequestInit = {}) => { const response = await fetch(`${base()}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(localStorage.getItem('token') ? { Authorization: `Bearer ${localStorage.getItem('token')}` } : {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload?.error || `Erro HTTP ${response.status}`); return payload as T; };
export const conversationsAPI = {
  list: (params: { search?: string; filter?: string; assignedUserId?: number } = {}) => { const query = new URLSearchParams({ channel: 'whatsapp' }); if (params.search) query.set('search', params.search); if (params.filter === 'unread') query.set('unread', 'true'); if (params.filter === 'ai' || params.filter === 'human') query.set('handlingMode', params.filter); if (params.assignedUserId) query.set('assignedUserId', String(params.assignedUserId)); return request<{ conversations: Conversation[] }>(`/api/conversations?${query.toString()}`); },
  detail: (id: number) => request<ConversationDetail>(`/api/conversations/${id}`),
  messages: (id: number) => request<{ messages: CommunicationMessage[]; hasMore?: boolean }>(`/api/conversations/${id}/messages`),
  activities: (id: number) => request<{ activities: ConversationActivity[] }>(`/api/conversations/${id}/activities`),
  markRead: (id: number) => request<{ success: boolean }>(`/api/conversations/${id}/read`, { method: 'PATCH' }),
  setHandling: (id: number, handlingMode: string) => request<{ success: boolean; handling_mode: string }>(`/api/conversations/${id}/handling`, { method: 'PATCH', body: JSON.stringify({ handling_mode: handlingMode }) }),
  assign: (id: number, assignedUserId: number | null) => request<{ success: boolean; assigned_user_id: number | null }>(`/api/conversations/${id}/assignment`, { method: 'PATCH', body: JSON.stringify({ assigned_user_id: assignedUserId }) }),
  send: (id: number, text: string) => request(`/api/conversations/${id}/messages`, { method: 'POST', headers: { 'Idempotency-Key': `chat:${id}:${Date.now()}` }, body: JSON.stringify({ type: 'text', text }) }),
};
