export type Conversation = { id: number; channel?: string; conversation_type?: "contact" | "group"; display_name?: string | null; profile_picture_url?: string | null; profile_picture_updated_at?: string | null; profile_picture_stale?: boolean | number; participant_count?: number | null; pinned_at?: string | null; archived_at?: string | null; manual_unread?: boolean | number; lead_id?: number | null; lead_name?: string | null; lead_phone?: string | null; lead_email?: string | null; lead_website?: string | null; lead_status?: string | null; lead_origin?: string | null; account_name?: string | null; account_phone?: string | null; assigned_user_id?: number | null; assigned_user_name?: string | null; status: string; handling_mode: string; unread_count: number; last_message_at?: string | null; last_message_text?: string | null; last_message_type?: string | null; last_message_direction?: string | null };
export type CommunicationMessage = { id: number; direction: string; sender_name?: string | null; body_text?: string | null; delivery_status?: string | null; starred_at?: string | null; message_type?: string | null; created_at: string; sent_at?: string | null; provider?: string | null; media_storage_path?: string | null; media_mime_type?: string | null; media_filename?: string | null; media_size_bytes?: number | null; media_duration_seconds?: number | null; media_width?: number | null; media_height?: number | null; media_status?: string | null; quoted_message_id?: number | null; metadata?: string | Record<string, unknown> | null };
export type ConversationLabel = { id: number; name: string; color: string };
export type ConversationDetail = Conversation & { ai_agent_id?: number | null; lead_city?: string | null; lead_state?: string | null; lead_category?: string | null; lead_created_at?: string | null; lead_budget?: string | null; lead_labels?: ConversationLabel[]; assigned_user_email?: string | null };
export type WhatsAppProfile = { profilePictureUrl: string | null; displayName: string | null; participantCount: number | null; participants?: Array<{ name: string | null; phone?: string | null; profilePictureUrl?: string | null; role: string }>; cached?: boolean; unavailable?: boolean };
export type ConversationActivity = { id: number; title: string; description?: string | null; type: string; created_at: string; actor_name?: string | null };
export type SharedConversationItem = Pick<CommunicationMessage, "id" | "direction" | "body_text" | "message_type" | "media_mime_type" | "media_filename" | "media_size_bytes" | "media_duration_seconds" | "media_width" | "media_height" | "created_at"> & { url?: string; domain?: string; excerpt?: string };
const base = () => import.meta.env.PROD ? '' : (import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001').replace(/\/api\/?$/, '').replace(/\/+$/, '');
export const conversationMediaUrl = (conversationId: number, messageId: number) => `${base()}/api/conversations/${conversationId}/messages/${messageId}/media`;
class ConversationsApiError extends Error {
  code?: string;
  status: number;
  constructor(message: string, status: number, code?: string) { super(message); this.name = "ConversationsApiError"; this.status = status; this.code = code; }
}
const request = async <T>(path: string, options: RequestInit = {}) => { const isMultipart = options.body instanceof FormData; const response = await fetch(`${base()}${path}`, { ...options, headers: { ...(isMultipart ? {} : { 'Content-Type': 'application/json' }), ...(localStorage.getItem('token') ? { Authorization: `Bearer ${localStorage.getItem('token')}` } : {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new ConversationsApiError(payload?.error || `Erro HTTP ${response.status}`, response.status, payload?.code); return payload as T; };
export const conversationsAPI = {
  list: (params: { search?: string; filter?: string; assignedUserId?: number } = {}) => { const query = new URLSearchParams({ channel: 'whatsapp' }); if (params.search) query.set('search', params.search); if (params.filter === 'archived') query.set('archived', 'true'); if (params.filter === 'unread') query.set('unread', 'true'); if (params.filter === 'ai' || params.filter === 'human') query.set('handlingMode', params.filter); if (params.assignedUserId) query.set('assignedUserId', String(params.assignedUserId)); return request<{ conversations: Conversation[] }>(`/api/conversations?${query.toString()}`); },
  detail: (id: number) => request<ConversationDetail>(`/api/conversations/${id}`),
  messages: (id: number, beforeId?: number) => request<{ messages: CommunicationMessage[]; hasMore?: boolean }>(`/api/conversations/${id}/messages${beforeId ? `?beforeId=${beforeId}` : ""}`),
  searchMessages: (id: number, term: string, beforeId?: number) => request<{ messages: CommunicationMessage[]; total: number; hasMore: boolean }>(`/api/conversations/${id}/messages/search?q=${encodeURIComponent(term)}${beforeId ? `&beforeId=${beforeId}` : ""}`),
  shared: (id: number, type: "media" | "documents" | "links", beforeId?: number) => request<{ items: SharedConversationItem[]; hasMore: boolean }>(`/api/conversations/${id}/shared?type=${type}${beforeId ? `&beforeId=${beforeId}` : ""}`),
  refreshProfile: (id: number, force = false) => request<WhatsAppProfile>(`/api/conversations/${id}/profile/refresh`, { method: "POST", body: JSON.stringify({ force }) }),
  updateLeadBudget: (leadId: number, budget: string | null) => request(`/api/prospection/prospects/${leadId}`, { method: "PATCH", body: JSON.stringify({ metadata: { budget } }) }),
  activities: (id: number) => request<{ activities: ConversationActivity[] }>(`/api/conversations/${id}/activities`),
  markRead: (id: number) => request<{ success: boolean }>(`/api/conversations/${id}/read`, { method: 'PATCH' }),
  markUnread: (id: number) => request<{ success: boolean }>(`/api/conversations/${id}/unread`, { method: 'PATCH' }),
  setPinned: (id: number, pinned: boolean) => request<{ success: boolean; pinned: boolean }>(`/api/conversations/${id}/pin`, { method: 'PATCH', body: JSON.stringify({ pinned }) }),
  setArchived: (id: number, archived: boolean) => request<{ success: boolean; archived: boolean }>(`/api/conversations/${id}/archive`, { method: 'PATCH', body: JSON.stringify({ archived }) }),
  hide: (id: number) => request<{ success: boolean; deletionMode: string }>(`/api/conversations/${id}`, { method: 'DELETE' }),
  setStarred: (conversationId: number, messageId: number, starred: boolean) => request<{ success: boolean; starred: boolean }>(`/api/conversations/${conversationId}/messages/${messageId}/star`, { method: 'PATCH', body: JSON.stringify({ starred }) }),
  favorites: (id: number, beforeId?: number) => request<{ messages: CommunicationMessage[]; hasMore: boolean }>(`/api/conversations/${id}/favorites${beforeId ? `?beforeId=${beforeId}` : ''}`),
  setHandling: (id: number, handlingMode: string) => request<{ success: boolean; handling_mode: string }>(`/api/conversations/${id}/handling`, { method: 'PATCH', body: JSON.stringify({ handling_mode: handlingMode }) }),
  assign: (id: number, assignedUserId: number | null) => request<{ success: boolean; assigned_user_id: number | null }>(`/api/conversations/${id}/assignment`, { method: 'PATCH', body: JSON.stringify({ assigned_user_id: assignedUserId }) }),
  send: (id: number, text: string, quotedMessageId?: number | null) => request(`/api/conversations/${id}/messages`, { method: 'POST', headers: { 'Idempotency-Key': `chat:${id}:${crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`}` }, body: JSON.stringify({ type: 'text', text, quotedMessageId: quotedMessageId || undefined }) }),
  sendMedia: (id: number, file: File | Blob, type: "image" | "audio" | "video" | "document", caption?: string, filename?: string, quotedMessageId?: number | null) => { const form = new FormData(); form.append("type", type); form.append("file", file, filename || (file instanceof File ? file.name : `audio-${Date.now()}.webm`)); if (caption) form.append("caption", caption); if (quotedMessageId) form.append("quotedMessageId", String(quotedMessageId)); return request(`/api/conversations/${id}/messages`, { method: "POST", headers: { "Idempotency-Key": `chat:${id}:${crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`}` }, body: form }); },
};
