const TRIGGER_TYPES = Object.freeze([
  'lead.created',
  'lead.updated',
  'lead.status_changed',
  'lead.pipeline_stage_changed',
  'lead.tag_added',
  'lead.tag_removed',
  'lead.assigned',
  'lead.converted',
  'activity.created',
  'activity.completed',
]);

const STEP_TYPES = Object.freeze(['condition', 'wait', 'action', 'finish']);

const ACTION_TYPES = Object.freeze([
  'lead.update_status',
  'lead.move_pipeline_stage',
  'lead.add_tag',
  'lead.remove_tag',
  'lead.assign_user',
  'activity.create',
  'notification.create',
  'email.send',
  'whatsapp.send',
  'lead.remove_assignee',
  'lead.update_field',
  'lead.add_note',
  'lead.move_pipeline',
  'activity.create_task',
  'activity.create_call',
  'activity.create_follow_up',
  'activity.complete',
  'wait.period',
  'whatsapp.send_message',
  'whatsapp.send_template',
  'whatsapp.send_file',
  'whatsapp.send_image',
  'instagram.send_direct',
  'instagram.follow',
  'instagram.unfollow',
  'instagram.like_post',
  'instagram.comment',
  'data.copy_field',
  'data.clear_field',
  'webhook.send',
  'http.request',
  'ai.run',
]);

const ACTION_CATALOG = Object.freeze([
  { id: 'lead.update_status', name: 'Alterar status do Lead', category: 'crm', availability: 'coming_soon' },
  { id: 'lead.assign_user', name: 'Atribuir responsavel', category: 'crm', availability: 'coming_soon' },
  { id: 'lead.remove_assignee', name: 'Remover responsavel', category: 'crm', availability: 'coming_soon' },
  { id: 'lead.update_field', name: 'Atualizar campo do Lead', category: 'data', availability: 'coming_soon' },
  { id: 'lead.add_note', name: 'Adicionar observacao', category: 'crm', availability: 'coming_soon' },
  { id: 'lead.add_tag', name: 'Adicionar etiqueta', category: 'crm', availability: 'coming_soon' },
  { id: 'lead.remove_tag', name: 'Remover etiqueta', category: 'crm', availability: 'coming_soon' },
  { id: 'lead.move_pipeline_stage', name: 'Mover para etapa', category: 'pipeline', availability: 'coming_soon' },
  { id: 'lead.move_pipeline', name: 'Mover para pipeline', category: 'pipeline', availability: 'coming_soon' },
  { id: 'activity.create', name: 'Criar atividade', category: 'crm', availability: 'coming_soon' },
  { id: 'activity.create_task', name: 'Criar tarefa', category: 'crm', availability: 'coming_soon' },
  { id: 'activity.create_call', name: 'Criar ligacao', category: 'crm', availability: 'coming_soon' },
  { id: 'activity.create_follow_up', name: 'Criar follow-up', category: 'crm', availability: 'coming_soon' },
  { id: 'activity.complete', name: 'Concluir atividade', category: 'crm', availability: 'coming_soon' },
  { id: 'notification.create', name: 'Criar notificacao interna', category: 'crm', availability: 'coming_soon' },
  { id: 'wait.period', name: 'Aguardar periodo', category: 'time', availability: 'coming_soon' },
  { id: 'email.send', name: 'Enviar e-mail', category: 'communication', availability: 'requires_integration', requiredIntegration: 'email' },
  { id: 'whatsapp.send_message', name: 'Enviar mensagem no WhatsApp', category: 'communication', availability: 'requires_integration', requiredIntegration: 'whatsapp' },
  { id: 'whatsapp.send', name: 'Enviar mensagem no WhatsApp', category: 'communication', availability: 'requires_integration', requiredIntegration: 'whatsapp' },
  { id: 'whatsapp.send_template', name: 'Enviar template WhatsApp', category: 'communication', availability: 'requires_integration', requiredIntegration: 'whatsapp' },
  { id: 'whatsapp.send_file', name: 'Enviar arquivo no WhatsApp', category: 'communication', availability: 'requires_integration', requiredIntegration: 'whatsapp' },
  { id: 'whatsapp.send_image', name: 'Enviar imagem no WhatsApp', category: 'communication', availability: 'requires_integration', requiredIntegration: 'whatsapp' },
  { id: 'instagram.send_direct', name: 'Enviar mensagem no Direct', category: 'instagram', availability: 'requires_integration', requiredIntegration: 'instagram' },
  { id: 'instagram.follow', name: 'Seguir perfil', category: 'instagram', availability: 'requires_integration', requiredIntegration: 'instagram' },
  { id: 'instagram.unfollow', name: 'Deixar de seguir perfil', category: 'instagram', availability: 'requires_integration', requiredIntegration: 'instagram' },
  { id: 'instagram.like_post', name: 'Curtir publicacao', category: 'instagram', availability: 'coming_soon' },
  { id: 'instagram.comment', name: 'Comentar publicacao', category: 'instagram', availability: 'coming_soon' },
  { id: 'data.copy_field', name: 'Copiar valor entre campos', category: 'data', availability: 'coming_soon' },
  { id: 'data.clear_field', name: 'Limpar campo', category: 'data', availability: 'coming_soon' },
  { id: 'webhook.send', name: 'Webhook', category: 'integrations', availability: 'coming_soon' },
  { id: 'http.request', name: 'HTTP Request', category: 'integrations', availability: 'coming_soon' },
  { id: 'ai.run', name: 'Executar IA', category: 'integrations', availability: 'coming_soon' },
]);

const isSupported = (catalog, value) => catalog.includes(value);

module.exports = {
  TRIGGER_TYPES,
  STEP_TYPES,
  ACTION_TYPES,
  ACTION_CATALOG,
  isSupported,
};
