const assert = require('node:assert/strict');
const test = require('node:test');
const { adaptGooglePageSpeedResponse } = require('../services/pagespeed-google-adapter');
const { GOOGLE_ENDPOINT, MAX_RESPONSE_BYTES, PAGE_SPEED_TIMEOUT_MS, runGooglePageSpeed } = require('../services/pagespeed-google-provider');
assert.equal(PAGE_SPEED_TIMEOUT_MS, 90_000);
const { MAX_ATTEMPTS, acquirePageSpeedAnalysis, classifyPageSpeedError, normalizePageSpeedResponse, normalizeScore, normalizeWebsiteUrl, persistPageSpeedAnalysis, recordPageSpeedFailure, sanitizePageSpeedError, schedulePageSpeedAnalysis } = require('../services/pagespeed-performance');

const validFixture = { lighthouseResult: { categories: { performance: { score: 0.82 } }, audits: {
  'first-contentful-paint': { numericValue: 2000 }, 'largest-contentful-paint': { numericValue: 4100 }, 'cumulative-layout-shift': { numericValue: 0.06 }, 'speed-index': { numericValue: 3800 }, 'total-blocking-time': { numericValue: 420 }, 'server-response-time': { numericValue: 800 },
  'unused-javascript': { title: 'Reduce unused JavaScript', description: 'Reduce unused scripts.', details: { overallSavingsMs: 1200, overallSavingsBytes: 180000 } }, 'unknown-audit': { title: 'Ignore me', numericValue: 999 },
} }, field: { available: true, source: 'url', lcpMs: 2800, inpMs: 180, cls: 0.04 } };
const googleFixture = { lighthouseResult: { categories: { performance: { score: 0.82 } }, audits: { 'first-contentful-paint': { numericValue: 2000 }, 'largest-contentful-paint': { numericValue: 4100 }, 'cumulative-layout-shift': { numericValue: 0 }, 'speed-index': { numericValue: 3800 }, 'total-blocking-time': { numericValue: 420 }, 'server-response-time': { numericValue: 800 } } }, loadingExperience: { metrics: { LARGEST_CONTENTFUL_PAINT_MS: { percentile: 2800 }, INTERACTION_TO_NEXT_PAINT: { percentile: 180 }, CUMULATIVE_LAYOUT_SHIFT_SCORE: { percentile: 0 } } } };

test('normalizes the raw Lighthouse score strictly from 0 to 1', () => { assert.equal(normalizeScore(0.82), 82); assert.equal(normalizeScore(0), 0); assert.equal(normalizeScore(1), 100); assert.equal(normalizeScore(1.2), null); assert.equal(normalizeScore(50), null); assert.equal(normalizeScore('0.82'), null); assert.equal(normalizeScore(Number.NaN), null); assert.equal(normalizeScore(Infinity), null); });
test('normalizes lab metrics, URL field data and supported opportunities only', () => { const result = normalizePageSpeedResponse(validFixture); assert.equal(result.status, 'completed'); assert.equal(result.score, 82); assert.deepEqual(result.lab, { fcpMs: 2000, lcpMs: 4100, cls: 0.06, speedIndexMs: 3800, tbtMs: 420, ttfbMs: 800 }); assert.equal(result.field.source, 'url'); assert.equal(result.opportunities.length, 1); assert.equal(result.opportunities[0].id, 'unused-javascript'); assert.equal(result.opportunities[0].severity, 'high'); assert.deepEqual(result.opportunities[0].affectedMetrics, ['TBT', 'LCP']); });
test('missing field data is valid and does not become partial', () => { const result = normalizePageSpeedResponse({ lighthouseResult: { categories: { performance: { score: 0 } }, audits: { 'largest-contentful-paint': { numericValue: 1000 } } } }); assert.equal(result.status, 'completed'); assert.deepEqual(result.field, { available: false, source: null, lcpMs: null, inpMs: null, cls: null }); });
test('internal field contract accepts URL and origin only', () => { assert.equal(normalizePageSpeedResponse({ score: 0.5, field: { available: true, source: 'origin', lcpMs: 100, inpMs: 20, cls: 0 } }).field.source, 'origin'); assert.equal(normalizePageSpeedResponse({ score: 0.5, field: { available: true, source: 'other', lcpMs: 100 } }).field.available, false); });
test('Google adapter maps Lighthouse and URL CrUX without mixing the sources', () => { const result = adaptGooglePageSpeedResponse(googleFixture); assert.equal(result.score, 82); assert.deepEqual(result.lab, { fcpMs: 2000, lcpMs: 4100, cls: 0, speedIndexMs: 3800, tbtMs: 420, ttfbMs: 800 }); assert.deepEqual(result.field, { available: true, source: 'url', lcpMs: 2800, inpMs: 180, cls: 0 }); });
test('Google adapter falls back to origin CrUX and supports partial field data', () => { const result = adaptGooglePageSpeedResponse({ lighthouseResult: { categories: { performance: { score: 0 } }, audits: {} }, originLoadingExperience: { metrics: { LARGEST_CONTENTFUL_PAINT_MS: { percentile: 0 }, CUMULATIVE_LAYOUT_SHIFT_SCORE: { percentile: 0 } } } }); assert.deepEqual(result.field, { available: true, source: 'origin', lcpMs: 0, inpMs: null, cls: 0 }); });
test('Google adapter treats missing CrUX as unavailable and runtime errors as structured errors', () => { const result = adaptGooglePageSpeedResponse({ lighthouseResult: { categories: { performance: { score: 1 } }, audits: {} } }); assert.deepEqual(result.field, { available: false, source: null, lcpMs: null, inpMs: null, cls: null }); assert.throws(() => adaptGooglePageSpeedResponse({ lighthouseResult: { runtimeError: { code: 'NO_FCP' } } }), (error) => error.code === 'PAGESPEED_LIGHTHOUSE_RUNTIME_ERROR' && !error.stack.includes('NO_FCP')); });
test('Google adapter ignores buckets and unknown audits', () => { const result = adaptGooglePageSpeedResponse({ lighthouseResult: { categories: { performance: { score: 0.5 } }, audits: { unknown: { numericValue: 900 } } }, loadingExperience: { metrics: { LARGEST_CONTENTFUL_PAINT_MS: { distributions: [{ proportion: 1, min: 0, max: 100 }], percentile: '900' } } } }); assert.equal(result.field.available, false); assert.deepEqual(result.opportunities, []); });
test('Google provider builds the fixed HTTPS request through injected transport only', async () => { let request; const result = await runGooglePageSpeed({ url: 'https://public.example/path?q=1', apiKey: 'test-pagespeed-key', resolve: async () => [{ address: '93.184.216.34', family: 4 }], transport: async (value) => { request = value; return { statusCode: 200, body: JSON.stringify(googleFixture) }; } }); const parsed = new URL(request.url); assert.equal(parsed.origin + parsed.pathname, GOOGLE_ENDPOINT); assert.equal(parsed.searchParams.get('url'), 'https://public.example/path?q=1'); assert.equal(parsed.searchParams.get('strategy'), 'mobile'); assert.equal(parsed.searchParams.get('category'), 'performance'); assert.equal(parsed.searchParams.get('key'), 'test-pagespeed-key'); assert.equal(request.method, 'GET'); assert.equal(request.timeoutMs, PAGE_SPEED_TIMEOUT_MS); assert.equal(request.maxBytes, MAX_RESPONSE_BYTES); assert.equal(result.score, 82); });
test('Google provider rejects desktop, missing keys and unsafe URLs before transport', async () => { const transport = async () => { throw new Error('network must not run'); }; await assert.rejects(() => runGooglePageSpeed({ url: 'https://public.example', strategy: 'desktop', apiKey: 'test', transport }), /mobile/); await assert.rejects(() => runGooglePageSpeed({ url: 'https://public.example', apiKey: ' ', transport }), (error) => error.classification === 'configuration'); await assert.rejects(() => runGooglePageSpeed({ url: 'http://127.0.0.1', apiKey: 'test', resolve: async () => [{ address: '127.0.0.1', family: 4 }], transport }), (error) => error.classification === 'invalid_url'); });
test('Google provider maps HTTP, network, timeout and invalid JSON errors without secrets', async () => { const base = { url: 'https://public.example', apiKey: 'test-pagespeed-key', resolve: async () => [{ address: '93.184.216.34', family: 4 }] }; for (const [status, classification] of [[400, 'invalid_url'], [401, 'configuration'], [403, 'configuration'], [404, 'invalid_response'], [408, 'transient'], [429, 'quota'], [500, 'transient']]) await assert.rejects(() => runGooglePageSpeed({ ...base, transport: async () => ({ statusCode: status, body: JSON.stringify({ error: { status: 'SECRET_BODY' } }) }) }), (error) => error.statusCode === status && error.classification === classification && !error.message.includes('test-pagespeed-key')); await assert.rejects(() => runGooglePageSpeed({ ...base, transport: async () => ({ statusCode: 200, body: '{bad' }) }), (error) => error.code === 'PAGESPEED_INVALID_RESPONSE'); await assert.rejects(() => runGooglePageSpeed({ ...base, transport: async () => { throw Object.assign(new Error('Bearer test-pagespeed-key'), { code: 'ETIMEDOUT' }); } }), (error) => error.classification === 'transient' && !error.message.includes('test-pagespeed-key')); });
test('Google provider converts runtimeError into a safe invalid response', async () => { await assert.rejects(() => runGooglePageSpeed({ url: 'https://public.example', apiKey: 'test-pagespeed-key', resolve: async () => [{ address: '93.184.216.34', family: 4 }], transport: async () => ({ statusCode: 200, body: JSON.stringify({ lighthouseResult: { runtimeError: { code: 'PRIVATE_DETAIL' } } }) }) }), (error) => error.code === 'PAGESPEED_LIGHTHOUSE_RUNTIME_ERROR' && error.classification === 'invalid_response' && !error.message.includes('PRIVATE_DETAIL')); });
test('provider classifications remain stable through classifyPageSpeedError', async () => { const base = { url: 'https://public.example', apiKey: 'test-pagespeed-key', resolve: async () => [{ address: '93.184.216.34', family: 4 }] }; for (const [status, expected] of [[400, 'invalid_url'], [401, 'configuration'], [403, 'configuration'], [404, 'invalid_response'], [408, 'transient'], [429, 'quota'], [500, 'transient'], [502, 'transient'], [503, 'transient']]) await assert.rejects(() => runGooglePageSpeed({ ...base, transport: async () => ({ statusCode: status, body: '{}' }) }), (error) => classifyPageSpeedError(error) === expected); assert.equal(classifyPageSpeedError(Object.assign(new Error('arbitrary'), { classification: 'transient' })), 'invalid_response'); });
test('transport errors never expose API keys or website URLs', async () => { const key = 'test-pagespeed-key'; const site = 'https://cliente-exemplo.com/caminho?foo=bar'; await assert.rejects(() => runGooglePageSpeed({ url: 'https://public.example', apiKey: key, resolve: async () => [{ address: '93.184.216.34', family: 4 }], transport: async () => { throw new Error(`request failed: https://www.googleapis.com/pagespeedonline/v5/runPagespeed?key=${key} site=${site}`); } }), (error) => !error.message.includes(key) && !error.message.includes(site) && !error.code.includes(key) && !String(error.providerCode).includes(key) && !String(error.classification).includes(key)); });
test('redirect status is rejected without following it', async () => { await assert.rejects(() => runGooglePageSpeed({ url: 'https://public.example', apiKey: 'test-pagespeed-key', resolve: async () => [{ address: '93.184.216.34', family: 4 }], transport: async () => ({ statusCode: 301, body: '', headers: { location: 'https://other.example' } }) }), (error) => error.code === 'PAGESPEED_INVALID_RESPONSE' && classifyPageSpeedError(error) === 'invalid_response'); });
test('PageSpeed blocks local, link-local and mixed DNS destinations before transport', async () => {
  const cases = [
    ['http://[::1]', undefined],
    ['http://169.254.10.20', undefined],
    ['http://[fe80::1]', undefined],
    ['https://private.example', [{ address: '10.0.0.1', family: 4 }]],
    ['https://mixed.example', [{ address: '93.184.216.34', family: 4 }, { address: '192.168.1.10', family: 4 }]],
  ];
  for (const [url, answers] of cases) {
    let called = false;
    await assert.rejects(() => runGooglePageSpeed({ url, apiKey: 'test-pagespeed-key', resolve: async () => answers, transport: async () => { called = true; return { statusCode: 200, body: '{}' }; } }), (error) => error.classification === 'invalid_url');
    assert.equal(called, false);
  }
});
test('malformed and runtime-error payloads fail without inventing metrics', () => { assert.equal(normalizePageSpeedResponse(null).status, 'failed'); assert.equal(normalizePageSpeedResponse({ runtimeError: { code: 'FAILED' } }).status, 'failed'); assert.equal(normalizePageSpeedResponse({ lighthouseResult: { categories: {}, audits: {} } }).lab, null); });
test('website validation is syntactic and rejects unsupported schemes', () => { assert.equal(normalizeWebsiteUrl('example.com'), 'https://example.com/'); assert.equal(normalizeWebsiteUrl('ftp://example.com'), null); assert.equal(normalizeWebsiteUrl('javascript:alert(1)'), null); });

test('schedule validates ownership inputs, deduplicates and respects valid cache', async () => {
  const calls = [];
  const connection = { execute: async (sql) => { calls.push(sql); return sql.includes('FROM lead_pagespeed_analyses') ? [[], []] : sql.includes('FROM prospects') ? [[{ id: 4, owner_user_id: 2 }], []] : [{ affectedRows: 1, insertId: 9 }, []]; }, beginTransaction: async () => {}, commit: async () => {}, rollback: async () => {} };
  assert.deepEqual(await schedulePageSpeedAnalysis({ connection, prospectId: 4, ownerUserId: 2, website: 'https://empresa.test', strategy: 'desktop' }), { scheduled: false, reason: 'invalid_strategy' });
  assert.deepEqual(await schedulePageSpeedAnalysis({ connection, prospectId: 4, ownerUserId: 2, website: 'https://empresa.test' }), { scheduled: true, status: 'pending', id: 9 });
  assert.equal(calls.length, 3);
  const cached = { execute: async (sql) => [sql.includes('FROM lead_pagespeed_analyses') ? [{ id: 9, status: 'completed', refresh_after: new Date(Date.now() + 1000) }] : [{ id: 4, owner_user_id: 2 }], []], beginTransaction: async () => {}, commit: async () => {}, rollback: async () => {} };
  assert.deepEqual(await schedulePageSpeedAnalysis({ connection: cached, prospectId: 4, ownerUserId: 2, website: 'https://empresa.test' }), { scheduled: false, reason: 'cache_valid', id: 9 });
});

test('scheduler does not reset processing jobs or valid snapshots', async () => { const connection = { execute: async (sql) => sql.includes('FROM prospects') ? [[{ id: 4, owner_user_id: 2 }], []] : [[{ id: 9, status: 'processing', refresh_after: new Date(Date.now() - 1000) }], []], beginTransaction: async () => {}, commit: async () => {}, rollback: async () => {} }; assert.deepEqual(await schedulePageSpeedAnalysis({ connection, prospectId: 4, ownerUserId: 2, website: 'https://empresa.test' }), { scheduled: false, reason: 'already_queued', id: 9 }); });

test('acquire uses transaction lock and persist stores normalized payload only', async () => {
  const calls = [];
  const connection = { beginTransaction: async () => calls.push('begin'), rollback: async () => calls.push('rollback'), commit: async () => calls.push('commit'), execute: async (sql) => { calls.push(sql); return sql.startsWith('SELECT') ? [[{ id: 12, attempt_count: 0 }], []] : [[], []]; } };
  const job = await acquirePageSpeedAnalysis({ connection });
  assert.equal(job.id, 12);
  assert.deepEqual(calls.slice(0, 3), ['begin', calls[1], calls[2]]);
  assert.equal(calls.includes('commit'), true);
  const status = await persistPageSpeedAnalysis({ connection, job, normalized: normalizePageSpeedResponse(validFixture) });
  assert.equal(status, 'completed');
  assert.equal(calls.some((value) => String(value).includes('UPDATE lead_pagespeed_analyses SET status')), true);
});

test('failure retries transient errors with deterministic backoff and preserves snapshot columns', async () => { const calls = []; const connection = { execute: async (sql, params) => { calls.push([sql, params]); return [[], []]; } }; const result = await recordPageSpeedFailure({ connection, job: { id: 12, attempt_count: 1 }, error: new Error('Bearer secret-token'), kind: 'transient' }); assert.equal(result.status, 'pending'); assert.equal(result.delayMinutes, 5); assert.match(result.lastError, /\[redacted\]/); assert.equal(calls[0][0].includes('score ='), false); const terminal = await recordPageSpeedFailure({ connection, job: { id: 12, attempt_count: MAX_ATTEMPTS }, error: new Error('quota'), kind: 'quota' }); assert.equal(terminal.status, 'failed'); });
test('error sanitizer limits content and removes credential-like values', () => { const value = sanitizePageSpeedError(new Error('Authorization: Bearer abc token=xyz https://user:pass@example.com/path'), 'configuration'); assert.ok(value.length <= 500); assert.equal(value.includes('abc'), false); assert.equal(value.includes('user:pass'), false); });
