const test = require('node:test');
const assert = require('node:assert/strict');
const { normalizePageSpeedInsightsResult, createPerformanceJob, getPerformanceJob, resetPerformanceJobs } = require('../services/pagespeed-insights-performance');

const fixture = { categories: { performance: { score: 0.87 } }, audits: { 'first-contentful-paint': { numericValue: 1200 }, 'largest-contentful-paint': { numericValue: 2400 }, 'cumulative-layout-shift': { numericValue: 0.04 }, 'speed-index': { numericValue: 1800 }, 'total-blocking-time': { numericValue: 220 }, 'server-response-time': { numericValue: 300 }, 'unused-javascript': { title: 'Remove unused JavaScript', description: 'Reduce JavaScript', details: { type: 'opportunity', overallSavingsMs: 400, overallSavingsBytes: 12000 } } } };

test('normaliza fixture PageSpeed como Lab Data e nunca Field Data', () => { const result = normalizePageSpeedInsightsResult(fixture); assert.equal(result.status, 'completed'); assert.equal(result.score, 87); assert.deepEqual(result.lab, { fcpMs: 1200, lcpMs: 2400, cls: 0.04, speedIndexMs: 1800, tbtMs: 220, ttfbMs: 300 }); assert.equal(result.field, null); assert.equal(result.source, 'pagespeed_insights'); assert.equal(result.opportunities.length, 1); });
test('normaliza resultado parcial com score nulo e mÃ©tricas ausentes', () => { const result = normalizePageSpeedInsightsResult({ audits: { 'first-contentful-paint': { numericValue: 1000 } } }); assert.equal(result.status, 'completed'); assert.equal(result.score, null); assert.equal(result.lab.lcpMs, null); });
test('rejeita JSON invÃ¡lido, runtime error e estratÃ©gia desktop', () => { assert.equal(normalizePageSpeedInsightsResult(null).status, 'failed'); assert.equal(normalizePageSpeedInsightsResult({ runtimeError: { code: 'NO_FCP' } }).errorCode, 'PAGESPEED_INVALID_RESPONSE'); assert.throws(() => normalizePageSpeedInsightsResult(fixture, 'desktop'), /Only mobile/); });
test('jobs efÃªmeros protegem ownership, TTL, concorrÃªncia e rate limit', async () => { resetPerformanceJobs(); const executor = async () => new Promise((resolve) => setTimeout(() => resolve(normalizePageSpeedInsightsResult(fixture)), 5)); const created = createPerformanceJob({ ownerUserId: 7, url: 'https://example.com', executor, now: 1000 }); assert.ok(created.job.token.length >= 64); assert.equal(getPerformanceJob({ token: created.job.token, ownerUserId: 8, now: 1000 }), null); assert.equal(createPerformanceJob({ ownerUserId: 7, url: 'https://example.com', executor, now: 1001 }).error, 'PAGESPEED_RATE_LIMIT'); await new Promise((resolve) => setTimeout(resolve, 15)); assert.equal(getPerformanceJob({ token: created.job.token, ownerUserId: 7, now: 1000 + 10 * 60 * 1000 + 1 }), null); });
test('provider ausente falha sem expor detalhes do processo', async () => { resetPerformanceJobs(); const created = createPerformanceJob({ ownerUserId: 9, url: 'https://example.com', executor: async () => { throw Object.assign(new Error('secret provider /tmp/x'), { code: 'PAGESPEED_UNAVAILABLE' }); } }); await new Promise((resolve) => setTimeout(resolve, 5)); const job = getPerformanceJob({ token: created.job.token, ownerUserId: 9 }); assert.equal(job.status, 'failed'); assert.equal(job.errorCode, 'PAGESPEED_UNAVAILABLE'); });
